# Generated by Django 4.2.4 on 2023-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Subtitulo', models.CharField(max_length=50)),
                ('Cuerpo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quien', models.CharField(max_length=50)),
                ('opinion', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
